spring:
  datasource:
    dynamic:
      # 多数据源的配置
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: hujing19960825
        username: hujing
        url: jdbc:mysql://localhost:3307/oa?characterEncoding=UTF-8&useSSL=false&serverTimeZone=Hongkong&autoReconnect=true&allowMultiQueries=true
        type: com.zaxxer.hikari.HikariDataSource
      slaver:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: hujing19960825
        username: hujing
        url: jdbc:mysql://localhost:3307/oa?characterEncoding=UTF-8&useSSL=false&serverTimeZone=Hongkong&autoReconnect=true&allowMultiQueries=true
        type: com.zaxxer.hikari.HikariDataSource
  application:
    name: base-boot
  redis:
    host: localhost
    password: bdth-redis@2019
    port: 16379
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: ['shutdown']
  endpoint:
    health:
      show-details: always
base:
  boot:
    system:
      open-dynamic-data-source: true
# Seata Configuration
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-tx-group
  service:
    vgroup-mapping:
      base-boot-tx-group: default
    grouplist:
      default: 127.0.0.1:8091
  config:
    type: file
    file:
      name: file.conf
  registry:
    type: file
    file:
      name: registry.conf
# RocketMQ Configuration
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: base-boot-producer-group
    retry-times-when-send-async-failed: 0
    send-message-timeout: 300000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-failed: 2